version: '3.9'
services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    hostname: jenkins
#     privileged: true
#     user: root
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
#       - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
      - 50000:50000
